testes automatizados - modulo auth
Flutterando/calamidade-backend pull request #28
Opened 2024-05-16 13:40 UTC by matheusgit1

Implementarão de testes automatizado para controller module auth

2024-05-16 14:03 UTC, Matheus-Lara commented
@matheusgit1 favor seu PR para branch development

2024-05-16 14:06 UTC, Matheus-Lara requested changes
favor apontar o PR para branch development

2024-05-16 15:02 UTC, matheusgit1 commented
> favor apontar o PR para branch development

Alteração feita

2024-05-16 18:36 UTC, gustavovalle23 requested changes
Muito bons testes. Ótima iniciativa adicionando testes no controller. 
Deixei alguns comentarios/sugestoes de melhoria, mas o mais importante é retirar o código que não é referente a essa PR

2024-05-16 18:36 UTC, gustavovalle23 commented on src/modules/auth/auth.controller.ts
> +  public async validateDocument(@Body() body: GetDocumentBodyDto): Promise<{
Acredito que esse código não deveria estar aqui. Aparentemente utilizando a branch https://github.com/Flutterando/calamidade-backend/pull/29 ?

2024-05-16 18:36 UTC, gustavovalle23 commented on src/database/seeds/cooperated/cooperated-seed.module.ts
> +  imports: [TypeOrmModule.forFeature([Cooperated])],
Nao relacionado a essa PR

2024-05-16 18:36 UTC, gustavovalle23 commented on src/database/seeds/cooperated/cooperated-seed.service.ts
> +import { Injectable } from "@nestjs/common";
Nao relacionado a essa PR

2024-05-16 18:54 UTC, matheusgit1 commented on src/modules/auth/auth.controller.spec.ts
> +const jwtService = new JwtService();
essa dependência é necessária pois é injetada no construtor do da classe AuthService, e não, não há à necessidade de mock desse serviço, uma vez que ele não depende de outro nem de conexões com serviços externos e não impedem os testes do controller

2024-05-16 18:57 UTC, matheusgit1 commented on src/modules/auth/auth.controller.ts
> +  public async validateDocument(@Body() body: GetDocumentBodyDto): Promise<{
apenas um conflito na mudança de branch. Resolvido!

2024-05-16 18:59 UTC, matheusgit1 commented on src/modules/auth/auth.service.ts
> +  async validateDocument(document: string): Promise<{ name: string | null; document: string | null }> {
Resolvido!

2024-05-17 19:03 UTC, gustavovalle23 reviewed
LGTM

2024-05-17 21:12 UTC, Matheus-Lara approved these changes

2024-05-18 00:37 UTC, merged