Validação de documentos - cooperados
Flutterando/calamidade-backend pull request #29
Opened 2024-05-16 13:42 UTC by matheusgit1

rota de validação de documentos para cooperados

2024-05-16 14:04 UTC, Matheus-Lara commented
@matheusgit1 favor apontar este PR para a branch de development também

2024-05-16 14:05 UTC, Matheus-Lara requested changes
favor apontar este PR para a branch de development

2024-05-16 15:03 UTC, matheusgit1 commented
> favor apontar este PR para a branch de development

Alteração feita

2024-05-16 17:14 UTC, gustavovalle23 commented on src/modules/auth/auth.controller.ts
> +  public async validateDocument(@Body() body: GetDocumentBodyDto): Promise<{
Eu diria que essa rota não faz muito sentido aqui. Se é referente ao dominio/módulo de de Cooperados, eu diria que deveria ficar no modulo de cooperados. Nós estamos importando e usando o CooperatedService dentro do modulo de autenticacao, que não está relacionado fortemente com autenticação

2024-05-16 17:16 UTC, gustavovalle23 commented on src/modules/auth/auth.service.ts
> +          errors: "Uncooperative",
Seria melhor enviar um erro mais específico ou mais legível. Ficaria meio dificil entender com "Uncooperative"

2024-05-16 17:33 UTC, gustavovalle23 commented on src/modules/auth/auth.service.ts
> +    console.log(user, validation);
Console.log nao necessario

2024-05-16 17:33 UTC, gustavovalle23 commented on src/modules/auth/auth.service.ts
> +    // if (user.provider !== AuthProvidersEnum.email) {
Nao precisamos mais dessa parte? Se nao precisamos, podemos excluir ja

2024-05-16 17:35 UTC, gustavovalle23 commented on src/modules/auth/auth.service.ts
> +      name: cooperated.firstName || "",
Qual é a razão pra esse nome? Só o primeiro nome é suficiente ou o frontend vai mostrar esse campo? Se for mostrar, não será necessário o nome completo? Os ambos os campos

2024-05-16 17:37 UTC, gustavovalle23 commented on src/modules/auth/auth.service.ts
> +      document: cooperated.document || "",
Se o documento foi validado, por que deveríamos considerar um numero em branco? Se o documento foi em branco, tem algum dado errado no banco. E mesmo assim o input hoje nao aceita documentos com menos de 11 caracteres

2024-05-16 17:38 UTC, gustavovalle23 commented on src/modules/auth/dto/auth-email-login.dto.ts
> +  // @Validate(IsExist, ['User'], {
Não precisamos mais dessa validacão? Caso não, diria pra remover de fato o codigo

2024-05-16 18:02 UTC, gustavovalle23 reviewed
Seria massa ver/alterar os testes e2e pra garantir a qualidade desses endpoints

2024-05-16 19:02 UTC, matheusgit1 commented on src/modules/auth/auth.controller.ts
> +  public async validateDocument(@Body() body: GetDocumentBodyDto): Promise<{
na task inicial 'auth/document/validate' essa a rota definida nos requisitos e nas task do trello, creio que faça sentido essa mudança mas não seria alterar o escopo que já havia sido definido?

2024-05-16 19:03 UTC, matheusgit1 commented on src/modules/auth/auth.controller.ts
> +  public async validateDocument(@Body() body: GetDocumentBodyDto): Promise<{
irei migrar para o modulo de cooperated

2024-05-16 19:37 UTC, gustavovalle23 commented on src/modules/cooperated/cooperated.service.ts
> +  async validateDocument(document: string): Promise<{name: string, document: string}> {
Como vamos retornar todos os parametros, podemos alterar o tipo pra Cooperated

2024-05-17 12:57 UTC, Matheus-Lara approved these changes

2024-05-17 12:57 UTC, merged