Feature/receipts
Flutterando/calamidade-backend pull request #39
Opened 2024-05-17 14:02 UTC by valdosouza

# Por que a mudança é necessária?
    Uma primeira parte foi feita, por que a dependencia (request) não foi atualizada.
   Esta tarefa deverá ser retomada assim que o request for finalidado

# Como a alteração foi abordada?
     Foi feito observando o modulo organization

# Como testar?
       Ainda não é possivel, pois essa tarefa foi adiantata, e ainda dependete da retomada desta mesma tarefa após a conclusão da dependencia

2024-05-17 16:56 UTC, gustavovalle23 commented on src/database/seeds/accident/accident-seed.service.ts
> +
```suggestion
    const countAccident = await this.accidentRepository.count({
      where: {
        requestId: 123456,  // Replace with the specific requestId you want to check for
      },
    });

    if (!countAccident) {
      await this.accidentRepository.save(
        this.accidentRepository.create({
          requestId: 123456,  // Replace with the specific requestId you want to seed
          fileld: 789,        // Replace with the specific field value you want to seed
        }),
      );
      console.info('Accident created');
    } else {
      console.info('Accident with the specified requestId already exists. No action taken.');
    }
  }

```

2024-05-17 17:10 UTC, gustavovalle23 requested changes
Adoraria ver alguns testes e2e pra ter certeza de que os endpoints estao funcionando

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/accident/accident.controller.spec.ts
Nao estamos testando nada realmente aqui. Podemos remover esse arquivo ou implementar os testes

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/accident/accident.service.spec.ts
Nao estamos testando nada realmente aqui. Podemos remover esse arquivo ou implementar os testes

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/accident/accident.service.ts
> +    console.log(createAccidentDto)
console.log desnecessario

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/accident/accident.service.ts
> +    return `This action returns all accident`;
Nao queremos implementar esse service? Caso nao, podemos remover o endpoint tambem

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/accident/accident.service.ts
> +    return `This action removes a #${id} accident`;
Mesma coisa aqui. Talvez implementar um soft delete?

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/accident/entities/accident.entity.ts
> +  requestId: number;
O padrao eh nullable: true. Atribuicao nao necessaria

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/receipts/entities/receipts.entity.ts
> +  requestId: number;
nullable: true nao necessario

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/receipts/receipts.controller.spec.ts
Nao estamos testando nada realmente aqui. Podemos remover esse arquivo ou implementar os testes

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/receipts/receipts.service.spec.ts
Nao estamos testando nada realmente aqui. Podemos remover esse arquivo ou implementar os testes

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/receipts/receipts.service.ts
> +    return `This action returns all receipts`;
Nao queremos implementar?

2024-05-17 17:10 UTC, gustavovalle23 commented on src/modules/receipts/receipts.service.ts
> +  }
Nao queremos implementar? Podemos remover

2024-05-18 13:18 UTC, alexanderbraga commented
Tivemos que fechar a PR pois tivemos urgência, e tivemos que criar outra para dar andamento mais rápido.

Muito obrigado, pelo inicio!

2024-05-18 13:18 UTC, closed without merging