create recipt entities
Flutterando/calamidade-backend pull request #52
Opened 2024-05-17 22:22 UTC by shogunrs

# Por que a mudança é necessária?
Descreva por que as alterações neste Pull Request são necessárias. Detalhe como surgiu a demanda e qual problema está sendo resolvido.

# Como a alteração foi abordada?
Descreva brevemente o que foi realizado na tarefa e as decisões tomadas.

# Como testar?
Aqui pode ser descrito (opcionalmente) como testar a feature caso exista algum passo manual específico para garantir que os revisores consigam testar a feature ou alteração.

2024-05-17 22:39 UTC, gustavovalle23 commented on src/modules/receipt/receipt.controller.spec.ts
Teste nao realizando nenhum assert. Nao necessario

2024-05-17 22:39 UTC, gustavovalle23 commented on src/modules/receipt/receipt.service.spec.ts
Teste nao realizando nenhum assert. Nao necessario

2024-05-17 22:39 UTC, gustavovalle23 commented on src/modules/receipt/receipt.service.ts
Nós já temos a Entity. Seria bem possivel ao menos implementar a interface com o Repository. Se for necessario alguma alteração de regra de negócio, podemos alterar depois

2024-05-17 22:39 UTC, gustavovalle23 commented on src/modules/receipt/dto/create-receipt.dto.ts
Como ja temos a entidade, conseguimos colocar o dto inteiro como está nesse momento

2024-05-18 00:36 UTC, Matheus-Lara requested changes
Rever as alterações que tão adicionando pacotes e classes de login social na diff (fb/twitter). Por gentileza remove-los do package.json e deixar a diff limpa apenas com as alterações relativas à tarefa de receipt (vi que tem algumas dessas alterações em outros files tbm). Imagino que se vc sincronizar o seu fork com a branch development a diff deve desaparecer

2024-05-18 01:23 UTC, alexanderbraga commented
Solicitou urgencias nas solicitações

2024-05-18 13:11 UTC, merged